### ISSUE TITLE
Missing args.py and gcn_lib

### ISSUE THREAD

**Issue by ghost** [CurryTang/Graph-LLM#1]
Hi CurryTang,

Thanks for you code! This is a solid and splendid job.  I have some problems when trying to reproduce the result: 

(1) There is no args.py or suitable package can provide the function "get_command_line_args()" in baseline.py:
line 1:        from args import *
...
line 338:   args = get_command_line_args()  

(2) The code of gcn_lib used in this work is absent.

Best Regards.

**Comment by CurryTang** [comment]
Thanks for pointing out this problem. I've added the missing files.
