### ISSUE TITLE
Can't find the experiment code of Table 16: Comparison of several different strategies to incorporate structural information in the prompts.

### ISSUE THREAD

**Issue by zhongjian-zhang** [CurryTang/Graph-LLM#10]
Hi CurryTang,

Thanks for you code! I can't find the experiment code of Table 16 in ego_graph.py. If you can futher explain the code of  Table 16 in the repo, I will appreciate it.

**Comment by CurryTang** [comment]
Hi, I think those prompt strategies are based on some basic string concatenations so that I didn't put them in the repo. The code can be found in the following gist https://gist.github.com/CurryTang/e44f8bddb773b7bf4348cf270f8ed19f

**Comment by zhongjian-zhang** [comment]
Thanks for your response!
