### ISSUE TITLE
Understanding the splits

### ISSUE THREAD

**Issue by amangupt01** [CurryTang/Graph-LLM#13]
Thanks for sharing the code base and datasets! We enjoyed reading the paper.

I have some confusion regarding the splits used in the code. Can you please explain the difference between "pl_fixed", "fixed", 
"pl_random" and "random"? Are they related to the low_label and high_label settings mentioned in the paper?

When we set the low_labels_test argument to 1 with random split it still directs to a [60-20 split](https://github.com/CurryTang/Graph-LLM/blob/8033cf36fc2085ecd7c14aeea7834f1f0cbb8114/data.py#L202) of the dataset which is contrary to what is mentioned in the paper. Am I missing something here?

Thanks in Advance!

**Comment by CurryTang** [comment]
Hi, fixed refers to the low label rate mentioned in the paper (20 labels per class, 'fixed' means usually this is given as the official split) while random refers to 60% setting. pl is the pseudo labels given by the [TAPE](https://github.com/XiaoxinHe/TAPE). ` low_labels_test` is related to the few-shot setting mentioned in the annotation part.
