### ISSUE TITLE
I do not found the module ogbn_products

### ISSUE THREAD

**Issue by crebollobr** [CurryTang/Graph-LLM#17]
WANDB_DISABLED=True python lmfinetune.py --dataset cora --split random --batch_size=9 --label_smoothing 0.3 --seed_num 5

Traceback (most recent call last):
  File "/root/CONDA/LIXO/Graph-LLM/lmfinetune.py", line 8, in <module>
    from data import set_seed_config
  File "/root/CONDA/LIXO/Graph-LLM/data.py", line 39, in <module>
    from ogbn_products import get_raw_dataset
ModuleNotFoundError: No module named 'ogbn_products'

I do not found the module ogbn_products

**Comment by Ma-fee** [comment]
I do not find the module ogbn_products either. Do you solve the problem?

**Comment by CurryTang** [comment]
Should be fixed now. (This code repo is pretty old, for these TAG datasets, I recommend using https://github.com/CurryTang/TSGFM)
