### ISSUE TITLE
There seems to be a problem with the dataset citeseer～

### ISSUE THREAD

**Issue by user-AC** [CurryTang/Graph-LLM#3]
Thanks for the great work!

I downloaded small_data.zip from Google Drive, but the data.edge_index in the citeseer_random_sbert.pt is weird, it only contains self-loop edges, such as
>citeseer_data.edge_index = 
> tensor([[1552, 642, 1552, ....],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[1552, 642, 1552, ....]])

How do I get the correct edge_index?

**Comment by CurryTang** [comment]
Thanks. I've updated the corresponding pt files

**Comment by user-AC** [comment]
Thanks!

**Comment by LarFii** [comment]
Thanks for sharing the datasets!

It seems to also have the same problem with the citeseer_random_tfidf.pt.

**Comment by CurryTang** [comment]
> Thanks for sharing the datasets!
> 
> It seems to also have the same problem with the citeseer_random_tfidf.pt.

I have updated the datasets in the google drive. You may check `citeseer2_XXX_XXX`
