### ISSUE TITLE
Question about the specific meaning of each category in citeseer.

### ISSUE THREAD

**Issue by user-AC** [CurryTang/Graph-LLM#5]
Hi, can you provide the specific meaning of each category in citeseer (we know that citeseer contains 6 categories, ML, AI, IR, DB, HCI, Agent)? 

For example, number '1' in  the citeseer_data.y corresponds to which? ML, AI, IR, DB, HCI, or Agent?

**Comment by CurryTang** [comment]
Hi, the name of each category can be accessed through the `label_names` attribute. After loading the pt file into `a`, you may access it through `a.label_names`, which is `['Agents', 'ML', 'IR', 'DB', 'HCI', 'AI']`

**Comment by user-AC** [comment]
Thanks!
