### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by minhquoc0712** [CurryTang/Graph-LLM#8]
Hi, thank you for your interesting research.

I have a question: What is the difference between LLM-as-Enhancers with Iterative structure proposed in the paper and GLEM?

**Comment by CurryTang** [comment]
Thanks for your interest in our project. LLMs-as-Enhancers with iterative structure is a framework while GLEM is a detailed implementation of this framework. We use GLEM to test the effectiveness of this framework in this paper.

**Comment by minhquoc0712** [comment]
Thank you. I understand now.
