### ISSUE TITLE
Question of KEA

### ISSUE THREAD

**Issue by DaDuo-c** [CurryTang/Graph-LLM#9]
Hi, thank you for your interesting research.

I have a question: Is the KEA method in your paper included in the project? If so, in which file?

**Comment by CurryTang** [comment]
Hi, for KEA, we first use a simple prompt to extract the entities based on node attributes and save them as a pt file (in `ego_graph.py`). Then, in `generate_pyg_data`, we generate the corresponding embeddings. Then, you may configure it in the ensemble string.

**Comment by DaDuo-c** [comment]
OK. Thank you very much！
